### PR TITLE
Serial tests should now run with Travis CI

### PR DESCRIPTION
**Pull request by aniabrown**
I decided that the easiest way to get serial and parallel tests running with Travis would be to split out the `PlatformEnv` object into a `ParallelEnv` object and a `SerialEnv` object that inherits from `PlatformEnv`. This simplifies the build system as it doesn't require two different object files to be created from `PlatformEnv.cc`, one with a compile time flag to enable MPI and one without. 

This API change requires the user to choose the correct combination of `SerialEnv` object and `#import serialEnv.h`, as with eg `SerialSaveData` and `#import serialSaveData.h`. The makefile has also changed slightly -- I have updated the BrioWu-SingleFluidIdeal and KelvinHelmholtz-SingleFluidRandomIdeal examples. 

Currently the travis build works by compiling all sources, including the parallel sources, into the `Cmin` library, and linking MPI to that library (The Cmin library contains both Cmin and METHOD, if I understand correctly). At the moment only the tests which use the serial sources are being run -- I still need to figure out how to link the custom main file used for parallel tests and how to call the tests in parallel using cmake. 

Question -- does travis currently run tests for all branches, or will we need to pull this into master to test if it's working?

Finally, calling `py.test` directly rather than using `python -m pytest` is now working for me using a python venv so I have reverted back to the old syntax -- hopefully `make tests` now works using anaconda python.

### CODE REVIEW

**Comment by AlexJamesWright** [comment]
I'm having trouble building with Cmake, where are the serialEnv.cc and parallelEnv.cc files? Cant see them in the Src dir.

Also once you commit and push travis will run the tests for that branch. You can check the status [here](https://travis-ci.org/github/AlexJamesWright/METHOD)

**Comment by aniabrown** [comment]
I forgot to add the files to git -- oops, sorry!

**Comment by AlexJamesWright** [comment]
Cool, the travis script now works on my machine but is stilll failing remotely with
```
$ cmake -H. -Bbuild
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find MPI_C (missing: MPI_C_LIB_NAMES MPI_C_HEADER_DIR MPI_C_WORKS) 
-- Could NOT find MPI_CXX (missing: MPI_CXX_LIB_NAMES MPI_CXX_HEADER_DIR MPI_CXX_WORKS) 
CMake Error at /usr/local/cmake-3.12.4/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find MPI (missing: MPI_C_FOUND MPI_CXX_FOUND)
```

**Comment by aniabrown** [comment]
I've removed the MPI dependency from the serial tests. From what I can see the mpi_develop branch is now passing tests -- https://travis-ci.org/github/AlexJamesWright/METHOD/builds/703520108 but this pull request hasn't rerun with the new commit yet? -- https://travis-ci.org/github/AlexJamesWright/METHOD/builds/703520115

**Comment by AlexJamesWright** [comment]
Not sure why travis is giving conflicting results. Ill merge assuming it will rerun the tests and pass...

Coverage dropping doesnt matter really

**Pull request merged**
