### PR TITLE
Mpi develop -- initial MPI vs serial regression testing system

### PR DESCRIPTION
**Pull request by aniabrown**
Contains a basic version of parallel CPU vs serial regressions tests, integrated into the METHOD testing system. 

Typing `make test` in the Tests/Serial folder will run serial unit tests, serial tests which output final data, parallel tests which output final data, and a test which compares both data sets. Note that the result of the serial unit tests is summarised directly after the serial unit tests. The result of the regression tests are summarised at the very end.

`make compare` will run just the relevant tests which write output data in serial and parallel, and the comparison test. 

Currently implemented regression tests are based on the KelvinHelmoltz/SingleFluidIdealRandom and BrioWu/SingleFluidIdeal examples. The following combinations are implemented:
{RK2, RKSplit} x {Periodic boundary, Outflow boundary, Flow boundary} x {BrioWuSingleFluid, KHRandomInstabilitySingleFluid}. All are in 2D and use SRMHD only. 

All of these combinations pass other than KHRandomInstabilitySingleFluid with non-periodic boundary conditions. **Question -- does it make physical sense to use KHRandomInstabilitySingleFluid with Outflow or Flow BC? If so, will look for bugs, otherwise will remove from the list of tests.**

Currently neither the imex nor the fvs regression tests that were in the testing system originally work, possibly due to a bug in Outflow periodic bcs in 2D that was fixed as part of this PR -- I am investigating but those tests are disabled for now.

### CODE REVIEW

**Comment by IanHawke** [comment]
I can't think of any reason why KHI Random with different BCs shouldn't "work" in the sense of doing the same in parallel and serial. It doesn't make much physical sense. I wonder if it "fails" in the sense of producing negative densities of C2P failing. It would be interesting to know if the test works if it's only running a couple of timesteps.

**Comment by aniabrown** [comment]
BCS: The KHI Random test with Flow bc is not throwing any errors over four timesteps -- can I take that to mean the C2P is not failing? I tried reducing the number of timesteps to 2, but the test still fails. For what it's worth, if I increase the domain size to nx=ny=64, the test succeeds at 4 timesteps but fails at a larger number -- it seems there is some very small error that is being introduced, presumably due to the parallel implementation of the Outflow bc. I can step through this with a debugger and see if I can find where exactly the difference is. 

GPU tests: I've updated the line in Tests/Parallel/Src/compare...py, thanks

Python: I need to look further into this -- I haven't used anaconda much. I'm using a venv, which for me only worked if I called pytest as a module of my python installation with `python -m pytest -v Src/compareParallelAndSerial.py`. I'm not sure why `py.test` can't be found in that instance. I'm also not sure why the anaconda installation of python doesn't have pytest as a module. I'll see if I can find a way to detect if there is a pytest installation available but suspect I might need to require the user to define something in the makefile.

**Comment by AlexJamesWright** [comment]
So it does sound like there is something wrong with the parallel implementation of the outflow BCs, fingers crossed its not too messy.

One other comment: The build for the mpi_develop branch is failing on travisCI. Currently this is because saveData.cc in the CMakeLists.txt in Project/Serial/ hasnt been updated to parallel/serialSaveData. Once doing that there is still a problem linking the MPI libraries. Couldn't figure out how to resolve this after a while though as I'm fairly inexperienced with CMake

**Comment by aniabrown** [comment]
Yep, it was indeed a bug -- a dumb thing to do with detecting whether a rank was on an external boundary. All tests in Tests/Serial should pass now

**Comment by aniabrown** [comment]
I'm going to merge this in to mpi (not master yet) and then work on python and cmake in another PR.

**Pull request merged**
