### PR TITLE
HDF5 Implementation

### PR DESCRIPTION
**Pull request by smangham**
Added serial and parallel save classes for saving to HDF5 data files. Serial requires serial HDF5 installed (uses the `h5c++` compiler wrapper), parallel requires parallel HDF5 with OpenMPI installed (uses the `h5pcc.openmpi` compiler wrapper). Example models using them exist in `Examples/KelvinHelmholtz/SingleFluidIdealRandomMPIHDF5`  and `Examples/KelvinHelmholtz/SingleFluidIdealRandomSerialHDF5`.

Tests are added to the `Scripts` directory: Several Python files for converting text outputs to HDF5, and for comparing HDF5 files to each other. There are bash scripts to build and run the examples, and convert and compare their outputs.

Tests are not plumbed into Travis or the proper test framework.

### CODE REVIEW

**Comment by aniabrown** [comment]
Added unit tests comparing the outputs of the serial and parallel HDF5 writers to the plain text writers. These tests convert the plain text output from SerialSaveData and ParallelSaveData writers to HDF5, then compare that HDF5 to HDF5 output written by SerialSaveDataHDF5 and ParallelSaveDataHDF5. 

Tests currently require that METHOD/Scripts be in PYTHONPATH.

**Comment by AlexJamesWright** [comment]
Apologies for taking *so* long to see to this! 
I'm having trouble saving data in parallel in hdf5 format. When I try to run on my machine I get stack smashing errors. How should I be running the tests? E.g. on my machine or should this only work on iridis using multiple nodes?

I've also made some changes to the Tests/CPU/Makefile so that I could actually get things to (partially) run on my machine, but I'm unsure if this will break things for the rest of you. Maybe you could check to see if it has at some point? Those changes are on a new branch: hdf5_alex

**Comment by aniabrown** [comment]
Hi Alex, thanks for the comments. Having access to multiple nodes should not be required but I did find it difficult to install hdf5 locally so ended up moving to Iridis 5 -- I had issues with conflicts between the serial and parallel versions of hdf5, as well as making sure parallel hdf5 was finding the right MPI library. 

I've added a folder IridisEnv in Scripts with setup instructions for how to run on Iridis -- could you have a look and see if those work for you? 

I'll take a look at your changes and see if I they break things on Iridis for me.

**Comment by aniabrown** [comment]
Aha -- at least part of the problem is due to me failing to commit a script (see above). Apologies!

**Comment by aniabrown** [comment]
I've simplified the build system for the hdf5 tests -- could you see if they build for you locally now Alex (on this branch)? You should hopefully only have to change CC in the Makefile.

The reason the Makefile was overly complex before was that I did not think we could rely on compiler wrappers with nvcc for the GPU version. Having taken another look, I think it should be possible to pass the parallel hdf5 compiler wrapper to nvcc.

**Comment by IanHawke** [comment]
Can confirm that the checkpoint-restart works for me, mostly looks good.

The one thing that springs to mind here is the random seed (`seed` in `main.cc`). I would usually encode this in the filename - that's how the output was dealt with previously - but I now wonder about also storing it in the h5 somewhere. That's a bit of a pain as it's not defined in all cases; if you can't think of an easy way of adding such optional data, let's put it as an issue for future work and we'll encode in the filename again for now.

**Comment by aniabrown** [comment]
I think adding optional data shouldn't be too much work. I believe attributes can be a short array, so I suggest the simplest solution is to store an array of floats as the global file attribute "optional_sim_args". This obviously isn't perfect as some of these may need to be cast to/from ints, but given there are likely to be few of these I don't think it would be a problem. There could  then be two optional arguments to Data, optional_sim_args and num_sim_args. 

I think incorporating HDF5 and checkpoint restart into the GPU version of METHOD is a higher priority, so I'd prefer to work on that first. 

Another lower priority thing this brings up -- the interface to Data is getting quite clunky. Currently if you want to set one of the args that's at the end you have to set all the args in between. Would it make sense to add some setter functions that let you initialise those vars independently?

I've added functionality for MPI + checkpoint restart in the latest commit to this PR, with the example SingleFluidIdealRandomMPIHDF5CheckpointRestart. Could you check if that is working correctly for you? If so I'd suggest we pull in this PR and I can open new ones for the other items mentioned here.

**Comment by IanHawke** [comment]
I will do the check at the beginning of next week before the next meeting.

Setter functions would be a long-term plan, yes. Thinking in Python terms this sounds like a job for a dictionary, but the C++ map functionality looks a bit painful in comparison. If you've got a clean plan already then I'd go with that; otherwise I'll look into how some other C++ codes do parameter parsing (thinking AMReX in particular).

**Comment by IanHawke** [comment]
MPI restart works for me. Am slightly confused by the two endTime's in the example file, but we can work that out tomorrow.

**Pull request merged**
